### ISSUE TITLE
Text color missing for tabs in unfocused pane

### ISSUE THREAD

**Issue by Chaphasilor** [praveenpuglia/tailwind-breeze#1]
Hey, I just wanted to try out this theme and noticed that there's an issue with the tab names.  
See for yourself:

![image](https://user-images.githubusercontent.com/18015147/95246457-cf95c800-0814-11eb-802a-492201a391a0.png)

All tabs in the *unfocused* except the currently selected one have 'invisible' filenames. Likely a color-issue. This also happens with more than two panes.

Would be awesome if you could fix this! :D

**Comment by praveenpuglia** [comment]
Absolutely. Let me fix it tonight! Thanks for reporting

**Comment by praveenpuglia** [comment]
Can you please also confirm if you are on Windows or Mac?

**Comment by praveenpuglia** [comment]
I would also like to get your feedback on the actual color scheme. If you happen to like it a ⭐️ would be amazing or if you have feedback on things to improve, do let me know

**Comment by Chaphasilor** [comment]
> Can you please also confirm if you are on Windows or Mac?

Windows 10 :)

**Comment by Chaphasilor** [comment]
> I would also like to get your feedback on the actual color scheme. If you happen to like it a ⭐️ would be amazing or if you have feedback on things to improve, do let me know

I'm planning to give the stars as soon as I can see all the text :P  
If that issue is fixed, I'll use it for a couple days and then leave you some feedback, sounds good?

**Comment by praveenpuglia** [comment]
Sounds good! Only give it if I deserve it. Been sucked into day job also, I have to find a windows machine before I can fix this.

**Comment by Chaphasilor** [comment]
Any updates? Or is there something I can help you with?

**Comment by praveenpuglia** [comment]
Hey! I have managed to find a windows computer. Will be fixing it tonight for sure.

**Comment by praveenpuglia** [comment]
Now this is how they look. Will do a release on Marketplace in a few mins. Thanks for reporting! 
![image](https://user-images.githubusercontent.com/313363/96014275-d307ff80-0e63-11eb-82f1-fc2ebcb52e49.png)

**Comment by Chaphasilor** [comment]
You got your stars ^^

**Comment by praveenpuglia** [comment]
Hey @Chaphasilor!, were you able to use the theme now? If so, feedback please.

**Comment by Chaphasilor** [comment]
Yeah, well I started using it yesterday (actually the night before, but not for long).  
I'll try it out for a few more days and write down some thoughts I have, then I'll open a new issue.

How's that sound? 🤔

**Comment by praveenpuglia** [comment]
Lovely!
