### ISSUE TITLE
Can't see selection on iTerm

### ISSUE THREAD

**Issue by tzohpilotl** [praveenpuglia/tailwind-breeze#3]
When I select some text I expect the background to adopt a color with some contrast but what I actually see is that the text changes its color to gray but the background color does not change making it hard to know what text you selected.

Let me know what information I can provide to help with the bug triage.

**Comment by praveenpuglia** [comment]
Can you please paste a screenshot of the issue?
The selection does change the background color to gray as shown here.

I use iterm as well.

![image](https://user-images.githubusercontent.com/313363/118246827-19881000-b4c0-11eb-9c39-7c49d701875c.png)

**Comment by praveenpuglia** [comment]
I am going to close it for now. Please feel free to open it up if the above is not what you meant.
